import { createClient } from "@/lib/supabase/server";
import { formatComplianceType } from "@/lib/utils";
import { NextResponse } from "next/server";

// Simple HTML-to-PDF via browser print — returns HTML with print styles
// For production, swap with @react-pdf/renderer or puppeteer
export async function GET(
  _req: Request,
  { params }: { params: Promise<{ clientId: string }> }
) {
  const { clientId } = await params;
  const supabase = await createClient();

  const { data: client } = await supabase
    .from("clients")
    .select("*")
    .eq("id", clientId)
    .single();

  if (!client) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const { data: auditLogs } = await supabase
    .from("audit_log")
    .select("*")
    .eq("client_id", clientId)
    .order("timestamp", { ascending: true });

  const { data: tasks } = await supabase
    .from("compliance_tasks")
    .select("*")
    .eq("client_id", clientId)
    .order("due_date");

  const logs = auditLogs ?? [];
  const taskList = tasks ?? [];
  const generatedAt = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" });

  const actionLabels: Record<string, string> = {
    reminder_sent: "Reminder Sent",
    delivered: "Delivered",
    opened: "Opened by Client",
    doc_uploaded: "Document Uploaded",
    filed: "Return Filed",
    escalated: "Escalated to Partner",
  };

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Liability Report — ${client.name}</title>
  <style>
    body { font-family: Arial, sans-serif; font-size: 12px; color: #111; padding: 40px; }
    h1 { font-size: 20px; color: #1e1b4b; }
    h2 { font-size: 14px; color: #374151; margin-top: 24px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 8px; }
    th, td { padding: 8px; border: 1px solid #e5e7eb; text-align: left; }
    th { background: #f9fafb; font-weight: bold; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 9999px; font-size: 10px; }
    .filed { background: #d1fae5; color: #065f46; }
    .overdue { background: #fee2e2; color: #991b1b; }
    .pending { background: #f3f4f6; color: #374151; }
    .footer { margin-top: 40px; font-size: 10px; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Compliance Liability Report</h1>
  <p><strong>Client:</strong> ${client.name} &nbsp;|&nbsp; <strong>PAN:</strong> ${client.pan ?? "N/A"} &nbsp;|&nbsp; <strong>GSTIN:</strong> ${client.gstin ?? "N/A"}</p>
  <p><strong>Generated:</strong> ${generatedAt} IST</p>
  <p style="color:#dc2626; font-size:11px;">This report is generated from an immutable audit log and can be presented in client disputes and ICAI disciplinary proceedings.</p>

  <h2>Compliance Tasks</h2>
  <table>
    <thead><tr><th>Compliance</th><th>Period</th><th>Due Date</th><th>Status</th></tr></thead>
    <tbody>
      ${taskList.map(t => `
        <tr>
          <td>${formatComplianceType(t.compliance_type)}</td>
          <td>${t.period}</td>
          <td>${t.due_date}</td>
          <td><span class="badge ${t.status}">${t.status.replace("_", " ")}</span></td>
        </tr>
      `).join("")}
      ${taskList.length === 0 ? '<tr><td colspan="4" style="text-align:center;color:#9ca3af;">No tasks</td></tr>' : ""}
    </tbody>
  </table>

  <h2>Communication Audit Trail</h2>
  <table>
    <thead><tr><th>Timestamp (IST)</th><th>Action</th><th>Channel</th><th>Message ID</th></tr></thead>
    <tbody>
      ${logs.map(l => `
        <tr>
          <td>${new Date(l.timestamp).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</td>
          <td>${actionLabels[l.action] ?? l.action}</td>
          <td>${l.channel ?? "—"}</td>
          <td style="font-family:monospace;font-size:10px;">${l.message_id ?? "—"}</td>
        </tr>
      `).join("")}
      ${logs.length === 0 ? '<tr><td colspan="4" style="text-align:center;color:#9ca3af;">No communication logged</td></tr>' : ""}
    </tbody>
  </table>

  <div class="footer">
    Total reminders sent: ${logs.filter(l => l.action === "reminder_sent").length} &nbsp;|&nbsp;
    Documents uploaded: ${logs.filter(l => l.action === "doc_uploaded").length} &nbsp;|&nbsp;
    Returns filed: ${logs.filter(l => l.action === "filed").length}
    <br/>Report generated by CA Compliance Shield · Immutable audit log · All times in IST
  </div>

  <script>window.onload = () => window.print();</script>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `inline; filename="liability-report-${client.name.replace(/\s+/g, "-")}.html"`,
    },
  });
}
