insert into compliance_calendar (compliance_type, frequency, standard_due_date) values
  ('GSTR1',           'monthly',     '11th of month'),
  ('GSTR1_QUARTERLY', 'quarterly',   '13th of month after quarter'),
  ('GSTR3B',          'monthly',     '20th of month'),
  ('GSTR3B_QUARTERLY','quarterly',   '22nd-24th of month after quarter'),
  ('GSTR9',           'annual',      '31st December'),
  ('TDS_PAYMENT',     'monthly',     '7th of month'),
  ('TDS_RETURN_24Q',  'quarterly',   '31st of month after quarter'),
  ('TDS_RETURN_26Q',  'quarterly',   '31st of month after quarter'),
  ('ADVANCE_TAX',     'quarterly',   '15th Jun/Sep/Dec/Mar'),
  ('ITR_NON_AUDIT',   'annual',      '31st July'),
  ('ITR_AUDIT',       'annual',      '31st October'),
  ('TAX_AUDIT_3CD',   'annual',      '30th September'),
  ('AOC4',            'annual',      'October-November'),
  ('MGT7',            'annual',      'October-November'),
  ('DIR3_KYC',        'annual',      '30th September'),
  ('MSME1',           'half-yearly', '30th April / 31st October'),
  ('PF',              'monthly',     '15th of month'),
  ('ESI',             'monthly',     '15th of month'),
  ('LLP_FORM11',      'annual',      '30th May');;
